home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('extras/', views.extras, name='extras'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path("story1/", include("story1.urls")),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

home/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context = {
        "type" : "index"
    }
    return render(request, "home/index.html", context)

def extras(request):
    context = {
        "type" : "extras"
    }
    return render(request, "home/extras.html", context)

story1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context = {
        "type" : "story1"
    }
    return render(request, "story1/index.html", context)

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Primary Meta Tags -->
    {% block title %}{% endblock %}
    <meta name="title" content="Jojo's Not So Bizarre Adventure">
    <meta name="description" content="A full stack developer based in Tangerang who tries to beat Dio. Find out how I beat him using the power of coding and Star Platinum!">
    <link rel="icon" href="{% static 'home/images/j.png' %}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://jojostory4.herokuapp.com/">
    <meta property="og:title" content="Jojo's Not So Bizarre Adventure">
    <meta property="og:description" content="A full stack developer based in Tangerang who tries to beat Dio.">
    <meta property="og:image" content="{% static 'home/images/kamaba.jpg' %}">

    <!-- Bootstrap CSS and Scripts -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

    {% block css %}{% endblock %}
</head>

<body>
    {% if type == "index" %}
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom fixed-top">
        <a class="navbar-brand" href="#"><img id="icon" src="{% static 'home/images/j.png' %}">ojo's Adventure</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <!-- empty-->
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link" href="#skills">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#experience">Experience</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:extras' %}">Extras</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story1:index' %}">Story 1</a>
                </li>
            </ul>
        </div>
    </nav>

    {% elif type == "extras" %}
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom fixed-top">
        <a class="navbar-brand" href="{% url 'home:index' %}"><img id="icon" src="{% static 'home/images/j.png' %}">ojo's Adventure</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">Experience</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Extras</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story1:index' %}">Story 1</a>
                </li>
            </ul>
        </div>
    </nav>

    {% elif type == "story1" %}
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom fixed-top">
        <a class="navbar-brand" href="{% url 'home:index' %}"><img id="icon" src="{% static 'home/images/j.png' %}">ojo's Adventure</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">Experience</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:extras' %}">Extras</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Story 1</a>
                </li>
            </ul>
        </div>
    </nav>
    {% endif %}

    {% block content %}
    {% endblock %}

    <footer class="page-footer font-small">
        <div class="footer-copyright text-center py-3">
            Made by Jojo, 2020
        </div>
    </footer>
</body>
</html>

home/templates/home/extras.html
{% extends "home/base.html" %}
{% load static %}

{% block title %}
	<title>Extras - Jojo's Adventure</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
{% endblock css %}

{% block content %}
    <div class="container p-5" id="home" align="center">
        <div class="col d-flex flex-column">
            <h2>Welcome to the other side of me.</h2>
            <p>Let me tell you some of my interests and personality!</p>
            <p><a href="{% url 'home:index' %}" class="btn btn-primary btn-lg">Go Home</a></p>
        </div>
    </div>

    <div class="container">
        <div class="row mb-5 m-1">
            <div class="col justify-content-center">
                <h3 class="text-left">Hobbies</h3>
                <ul>
                    <li>Sleeping</li>
                    <li>Eating Indomie</li>
                    <li>Learning languages</li>
                    <li>Enjoying JoJo memes</li>
                </ul>
            </div>
            <div class="col">
                <h3 class="text-left">Interests</h3>
                <ul>
                    <li>Girls (Hey, I'm straight)</li>
                    <li>Table tennis (It's fun to smack some balls)</li>
                    <li>Puzzles</li>
                    <li>Music (especially EDM)</li>
                </ul>
            </div>
        </div>
        <div class="row mb-5 m-1">
            <div class="col justify-content-center">
                <h3 class="text-left">Some of my strengths</h3>
                <ul>
                    <li>Wise</li>
                    <li>Good communication</li>
                    <li>Honest</li>
                    <li>Loyal</li>
                </ul>
            </div>
            <div class="col">
                <h3 class="text-left">Some fo my weaknesses</h3>
                <ul>
                    <li>Unpunctual</li>
                    <li>Timid</li>
                    <li>Afraid to take risks</li>
                    <li>Impatience</li>
                </ul>
            </div>
        </div>
        <div class="row mb-5 m-1">
            <div class="col justify-content-center">
                <h3 class="text-left">My anime favorites</h3>
                <ul>
                    <li>Rascal Does Not Dream of Bunny Girl Senpai</li>
                    <li>Noragami</li>
                    <li>Steins;Gate</li>
                    <li>Your Name</li>
                </ul>
            </div>
            <div class="col">
                <h3 class="text-left">Epic manga series</h3>
                <ul>
                    <li>Kaguya-sama: Love Is War</li>
                    <li>Rent-a-Girlfriend</li>
                    <li>Grand Blue</li>
                    <li>Horimiya</li>
                </ul>
            </div>
        </div>
        <div class="row mb-3 m-1 justify-content-center">
            <div class="col" align="center">
                <b>Miko wants to thank you for spending your time reading this page!</b>
                <img src="{% static 'home/images/miko.jfif' %}" class="img-fluid" alt="kawaii miko">
            </div>
        </div>
    </div>
{% endblock %}

home/templates/home/index.html
{% extends "home/base.html" %}
{% load static %}

{% block title %}
	<title>Welcome! - Jojo's Adventure</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
{% endblock %}
	
{% block content %}
    <div class="container" align="center" id="home">
        <img src="{% static 'home/images/kamaba.jpg' %}" class="img-fluid" alt="This is me" id="kamaba">
        <p><!--empty--></p>
        <h3>Hello, my name is </h3>
        <h1>Jonathan Amadeus Hartman</h1>
        <p class="lead text-justify">
            I'm a full stack developer based in Tangerang, Indonesia. I'm a bachelor student from
            Faculty of Computer Science, Universitas Indonesia. I've always been interested in web development 
            and data science. I'm planning to learn more frameworks to help maximizing project results. 
            I'm proficient in four languages and striving to learn more. I usually 
            translate Japanese manga as a hobby. I'm a curious, attentive, and determined to give my best in my projects. 
            I'm ready for coding and translating projects in the future.
        </p>
    </div>   

    <div class="container">
        <h2 class="text-center" id="skills">What skills do I have?</h2>

        <div class="container">
            <h3>Programming</h3>
            <div class="row">
                <div class="col-md-6 col-lg-4">
                        <h4>HTML/CSS/JS</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/htmlcss.png' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <p>I learned this by myself and did website projects from university course.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                        <h4>Python</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/python.png' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <p>I use this to do my data science projects and web scraping. I also learn Python 
                                frameworks such as Django and pandas.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                        <h4>Java</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/java.png' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <p>I use this to build GUI (with JavaFX) and make algorithms for automation.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
                <h3>Language</h3>
            <div class="row">
                <div class="col-md-6 col-lg-4">
                        <h4>English</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/uk.svg' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <b>Level:</b>
                            <p>Professional</p>
                            <b>Certification:</b>
                            <p>IELTS (7.5 overall)</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                        <h4>Japanese</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/japan.png' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <b>Level:</b>
                            <p>Professional</p>
                            <b>Certification:</b>
                            <p>JLPT N2 (98)</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                        <h4>French</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/france.png' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <b>Level:</b>
                            <p>Intermediate</p>
                            <b>Certification:</b>
                            <p>-</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
            <h2 id="experience">What experience do I have?</h2>
        <div class="container">
                <h3>Organizations</h3>
            <div class="row">
                <div class="col-md-6 col-lg-4">
                        <h4>COMPFEST</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/compfest.jpg' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <b>Position:</b>
                            <p>Software Engineer</p><br>
                            <p>Biggest IT festival run by students in Indonesia</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                        <h4>SISTEM</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/sistem.jfif' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <b>Position:</b>
                            <p>Knowledge Management Staff</p><br>
                            <p>A Fasilkom organization focused in information system and business</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                        <h4>OLIM UI</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/olim.jpg' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <b>Position:</b>
                            <p>Badminton Staff</p><br>
                            <p>Helped preparing equipments and serving as a line judge</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
                <h3>Projects</h3>
            <div class="row">
                <div class="col-md-6 col-lg-4">
                        <h4>YouTube Transcriptor</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/yutub.png' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <p>Transcripts YouTube videos. Uses JavaFX, Web Speech API, and youtube-dl.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                        <h4>Maungajar</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/roar.jpg' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <p>Learning management website in Fasilkom UI. Uses PHP and Django.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                        <h4>Project Corona</h4>
                    <div class="row">
                        <div class="col">
                            <img src="{% static 'home/images/corona.png' %}" class="img-thumbnail">
                        </div>
                        <div class="col">
                            <p>Analyzing data of COVID patients in Indonesia. Uses Python and pandas.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container education">
            <h2>What is my educational background?</h2>
            <br>
        <div class="row m-1">
            <div class="col-xl-3">
                <div class="row">
                    <img src="{% static 'home/images/mentir.png' %}" class="img-thumbnail">
                </div>
                <div class="row">
                    <b>SDK Menara Tirza</b>
                </div>
                <div class="row">
                    (2007-2013)
                </div>
            </div>
            <div class="col-xl-3">
                <div class="row">
                    <img src="{% static 'home/images/penabur.png' %}" class="img-thumbnail" id="penabur">
                </div>
                <div class="row">
                    <b>SMPK Penabur Gading Serpong</b>
                </div>
                <div class="row">
                    <p>(2013-2016)</p>
                </div>
                
            </div>
            <div class="col-xl-3">
                <div class="row">
                    <img src="{% static 'home/images/penabur.png' %}" class="img-thumbnail" id="penabur">
                </div>
                
                <div class="row">
                    <b>SMAK Penabur Gading Serpong</b>
                </div>
                
                <div class="row">
                    <p>(2016-2019)</p>
                </div>
                
            </div>
            <div class="col-xl-3">
                <div class="row">
                    <img src="{% static 'home/images/ui.png' %}" class="img-thumbnail">
                </div>
                
                
                <div class="row">
                    <b>Universitas Indonesia</b>
                </div>
                
                <div class="row">
                    <b>Bachelor of Computer Science</b>
                </div>
                <div class="row">
                    <p>(2019-present)</p>
                </div>
                
            </div>
        </div>
    </div>

    <div class="container contact">
            <h2 id="contact">Interested? Contact me at</h2>
            <br>
        <div class="row m-1">
            <div class="col-xl-3">
                <div class="row">
                    <a href="https://www.linkedin.com/in/jonathan-amadeus-hartman" target="_blank">
                        <img src="{% static 'home/images/linkedin.png' %}" class="img-thumbnail">
                    </a>      
                </div>
                <div class="row">
                    Connect with me
                </div>
            </div>
            <div class="col-xl-3">
                <div class="row">
                    <a href="mailto:jonathanamadeus95@gmail.com">
                        <img src="{% static 'home/images/gmail.png' %}" class="img-thumbnail">
                    </a>
                </div>
                <div class="row">
                    Email me
                </div>
            </div>
            <div class="col-xl-3">
                <div class="row">
                    <a href="https://line.me/ti/p/3OhfOVHNgO" target="_blank">
                        <img src="{% static 'home/images/line.svg' %}" class="img-thumbnail">
                    </a>
                </div>
                <div class="row">
                    Chat with me
                </div>
            </div>
            <div class="col-xl-3">
                <div class="row">
                    <a href="https://www.instagram.com/jonathan_ama/" target="_blank">
                        <img src="{% static 'home/images/instagram.png' %}" class="img-thumbnail">
                    </a>
                </div>
                <div class="row">
                    Follow me
                </div>
            </div>
        </div>
    </div>
{% endblock %}

story1/templates/story1/index.html
{% extends "home/base.html" %}
{% load static %}

{% block title %}
	<title>Story 1 - Jojo's Adventure</title>
{% endblock %}

{% block css %}
	<link rel="stylesheet" href="{% static 'home/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
{% endblock %}
	
{% block content %}
	<div id="home" class="container">
		<h1 class="text-center">Hi! I'm JONATHAN AMADEUS HARTMAN</h1>
		<div class="row">
			<div class="col-md-4">
				<img id="pose" class="img-fluid rounded-circle" src="{% static 'story1/images/foto_maungid_crop.jpg' %}" alt="me posing">
			</div>
			<div class="col-md-8">
				<h2>Profile</h2>		
				<table class="table">
					<tr>
						<th scope="row">DOB</th>
						<td>Tangerang, 9 June 2001</td>
					</tr>
					<tr>
						<th scope="row">Student ID</th>
						<td>1906400261</td>
					</tr>
					<tr>
						<th scope="row">Batch</th>
						<td>Maung 2019</td>
					</tr>
					<tr>
						<th scope="row">Hobby</th>
						<td>video games, table tennis</td>
					</tr>
					<tr>
						<th scope="row">Interest</th>
						<td>web development, linguistics, music, anime</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	
	<div class="container">
		<h2>A Tiny Description of Myself</h2>
		<div class="row m-1">
			<p class="lead">
				Hello there. My name is Jojo and I like coding. In my leisure time, I usually do all of my stuffs on bed. 
				I love trying new things even though I'm not very good at it.
			</p>
		</div>
		<div class="row m-1">
			<p class="lead">
				Wielding the incredibly powerful Star Platinum, he is the first JoJo introduced with a Stand, and is among 
				the most well-known characters of the series.
			</p>
		</div>
		<div class="row m-1">
			<p class="lead">
				By the way, I've learned enough Bootstrap that this page looks way cooler. You can see the legacy version
				of this page <a href="http://jojostory1.herokuapp.com">here</a>.
			</p>
		</div>
	</div>

	<div class="container">
		<h2>Educational Background</h2>
		<div class="row m-1">
			<table class="table">
				<tr>
					<th>YEAR</th>
					<th>INSTITUTE</th>
				</tr>
				<tr>
					<td>2019-present</td>
					<td>Universitas Indonesia</td>
				</tr>
				<tr>
					<td>2016-2019</td>
					<td>SMAK Penabur Gading Serpong</td>
				</tr>
				<tr>
					<td>2013-2016</td>
					<td>SMPK Penabur Gading Serpong</td>
				</tr>
				<tr>
					<td>2007-2013</td>
					<td>SDK Menara Tirza</td>
				</tr>
			</table>
		</div>
	</div>

	<div class="container">
		<h2>Contact Me</h2>
		<div class="row m-1">
			<div class="col d-flex flex-column">
				<p>Here's some links to my accounts. Feel free to ask anything! :)</p>
				<ul>
					<li><a href="https://www.linkedin.com/in/jonathan-amadeus-hartman" target="_blank">LinkedIn</a></li>
					<li><a href="https://gitlab.com/HardJoe" target="_blank">GitLab</a></li>
					<li><a href="https://instagram.com/jonathan_ama" target="_blank">Instagram</a></li>
					<li><a href="https://twitter.com/Jonathan_Ama" target="_blank">Twitter</a></li>
				</ul>
			</div>
		</div>
	</div>
{% endblock %}